### ISSUE TITLE
Implementează funcționalitate de subscribe la proiecte

### ISSUE THREAD

**Issue by LucianU** [code4romania/volunt-app#10]
Unii voluntarii sunt interesați de anumite proiecte și vor să știe când e nevoie de ajutor la ele. Dacă dau subscribe, pot fi notificați când apare ocazia de a ajuta. 
Notificările se pot face prin email, dacă nu există sistem de notificări în site.

**Comment by vitaliel** [comment]
@LucianU 

Ok, apare ocazia de ajutor, ce sa va face? Cum coodonatorul va anunța?

**Comment by LucianU** [comment]
@vitaliel, bună întrebare. Pentru că site-ul n-are notificări interne, putem trimite un email la toți subscriberii când apare o oportunitate.

**Comment by vitaliel** [comment]
@LucianU cine poate să alcătuiască scrisoarea pe care o vom trimite voluntarilor?

**Comment by vitaliel** [comment]
@LucianU deci eu mă gîndesc așa:

Voluntarul se poate singur înscrie în project și cînd se creează un opening, voi face un buton pe pagina opening/view "Email project members" care va trimite notificare.

Ce zici?
![captura de ecran din 2017 03 07 la 21 18 51](https://cloud.githubusercontent.com/assets/995/23673650/b8b2f636-037b-11e7-83ed-45286fc4f27f.png)

**Comment by LucianU** [comment]
@vitaliel, mă gândeam ca emailul să se trimită automat atunci când apare un opening. Altfel persoana care crează opening-ul s-ar putea să uite să trimită emailul. Avem vreun motiv să nu-l trimitem automat?

Cât privește textul emailului, putem cere ajutorul unui coleg de la comunicare să-l formuleze.

**Comment by vitaliel** [comment]
@LucianU propun să creem o sarcină separată pentru trimiterea emailurilor

**Comment by LucianU** [comment]
De acord. O fac acum. Pe asta o închid, pentru că ai implementat-o în #26.
