### ISSUE TITLE
Funcționalitate de export din pagina de căutare

### ISSUE THREAD

**Issue by LucianU** [code4romania/volunt-app#11]
Vrem să putem exporta în format csv rezultatele unei căutări. Fișierul ar trebui să conțină nume, adresa de email și skill-uri.

**Comment by LucianU** [comment]
Funcționalitatea ar sta cel mai bine pe pagina de afișare a voluntarilor. Acolo sunt niște filtre și prinde bine să putem exporta rezultate filtrate.

**Comment by vitaliel** [comment]
@LucianU aparent există csv export deja în site, iconița din dreapta de pe captură.

![csv-export-icon](https://cloud.githubusercontent.com/assets/995/23623803/0c438c78-02ac-11e7-978c-bb8ba797c45d.png)

Este implementat în JS.

**Comment by LucianU** [comment]
@vitaliel, ai dreptate. Nu mi-am dat seama. Asta înseamnă că ar trebui să facem mai evident butonul ăla. Altfel, nu știu câți o să realizeze ce funcție are.

**Comment by vitaliel** [comment]
@LucianU deci închidem acest PR și facem unul nou doar cu schimbarea iconiței?

**Comment by LucianU** [comment]
@vitaliel, da.
