### ISSUE TITLE
Șterge Acord de Confidențialitate din meniul Documente

### ISSUE THREAD

**Issue by LucianU** [code4romania/volunt-app#17]
Când faci hover pe Documente, apare "Acord de Confidențialitate". Acel document e specific Gov IT HUB, deci nu avem nevoie de el.

**Comment by vitaliel** [comment]
@LucianU să ascundem cu totul meniul documente?

**Comment by LucianU** [comment]
@vitaliel, momentan îl putem ascunde. Pe viitor s-ar putea să punem ceva acolo totuși.

**Comment by LucianU** [comment]
Implementat în #23.
