### ISSUE TITLE
Configurează trimiterea de emailuri

### ISSUE THREAD

**Issue by LucianU** [code4romania/volunt-app#24]
Probabil vom folosi Amazon SES.

**Comment by LucianU** [comment]
@octaviandavid, poți ajuta cu asta?

**Comment by vitaliel** [comment]
@LucianU Eu am un mail server: mail.webng.md, putem trimite prin el temporar sau permanent.

**Comment by LucianU** [comment]
E ok, @vitaliel. Deja folosim AWS pentru hosting, așa că putem folosi SES.

**Comment by LucianU** [comment]
Implementat în #52.
