### ISSUE TITLE
Resetare parolă uitată

### ISSUE THREAD

**Issue by LucianU** [code4romania/volunt-app#48]
Vrem să oferim posibilitatea unui user să-și reseteze singur parola, dacă a uitat-o.

**Comment by vitaliel** [comment]
@LucianU există funcționalitatea deja pe pagina de login:

![login-page](https://cloud.githubusercontent.com/assets/995/23798309/be828c38-05ac-11e7-9e12-b21a248797b5.png)

**Comment by LucianU** [comment]
Mi-a scăpat. Sorry!

**Comment by cvic** [comment]
Am incercat mai devreme sa-mi resetez parola
