### ISSUE TITLE
Fă clar că emailurile vin de la Code4Romania

### ISSUE THREAD

**Issue by LucianU** [code4romania/volunt-app#55]
Folosim `comunitate at domeniu` ca să trimitem emailuri. Asta înseamnă că cei care le primesc văd că vin din partea "comunitate". Ar trebui să apară că vin din partea "Code4Romania".

**Comment by vitaliel** [comment]
@LucianU 
Cum se spune aici: http://stackoverflow.com/a/5084380/27913
Poți pune 
```
export EMAIL_FROM="Code4Romania <email@address.com>"
```
Pe development merge.

**Comment by LucianU** [comment]
Într-adevăr. Mulțumesc, @vitaliel!
