### ISSUE TITLE
Setează mai multe roluri pentru un proiect

### ISSUE THREAD

**Issue by LucianU** [code4romania/volunt-app#59]
În primul rând, "leader" va fi redenumit în "coordonator". De asemenea, pentru coordonator poate fi ales orice voluntar, nu doar cei cu rol de "coordonator".

Apoi vor fi adăugate următoarele roluri:
- tech lead: orice user cu rol voluntar
- UX/UI: orice user cu rol voluntar
- communication lead (opțional): orice user cu rol voluntar
- core support tech: user cu rol coordonator
- core support non-tech: user cu rol coordonator

**Comment by vitaliel** [comment]
Cînd adaugi un user în proiect îi poți pune ce rol dorești, e string.

**Comment by LucianU** [comment]
@vitaliel, da uitasem de aia. Totuși avem o limitare. Vrem ca un proiect să aibă niște roluri standard. Altfel să nu poată să treacă la etapa următoare (vezi #67). Cum putem face asta? Creăm o listă de roluri standard și o opțiune "Altul" unde poate fi introdus orice?

**Comment by LucianU** [comment]
Cred că o soluție acceptabilă ar fi să facem un dropdown de roluri. Avem un număr limitat de roluri posibile. În felul ăsta putem verifica dacă un rol există când un proiect trece la stadiul următor.

**Comment by LucianU** [comment]
Roluri suportate în primă instanță:
- Developer
- UX/UI
- Comunicare
- Tech lead
- Coordonator
