### ISSUE TITLE
Bug: CSRF exception. Are cookies disabled?

### ISSUE THREAD

**Issue by LucianU** [code4romania/volunt-app#68]
S-a întâmplat în Chrome imediat după ce m-am logat. În loc să mă duc pe pagina de profil, m-a redirecționat către home page și mi-a apărut eroarea din titlu.

**Comment by LucianU** [comment]
Am găsit thread-ul ăsta, dar nu mi-e clar care ar fi soluția: https://github.com/rails/rails/issues/21948

@vitaliel, îți dă vreo idee?

**Comment by vitaliel** [comment]
@LucianU 
Trebuie de încercat monkey-patchul acesta: https://gist.github.com/killthekitten/b9a7b11530c44e788a31ec53e5ef0dad

fără secțiunea cu Warden

**Comment by vitaliel** [comment]
@LucianU s-a primit să repari?

**Comment by LucianU** [comment]
@vitaliel, nu mi-a mai apărut eroarea, dacă asta întrebi.

**Comment by cvic** [comment]
Am testat pe 4 browsere, nu a disparut. 

As vrea sa testez 
https://github.com/rosenfeld/rails-template-streaming-invalid-csrf-bug

**Comment by LucianU** [comment]
Please do!

**Comment by ancazapuc9** [comment]
Tested the latest version on Chrome, Firefox, Safari (53, 58 versions) on a Mac OS. 
Rails 5 + ruby 2.3.1p112 
I could not reproduce the problem ( for me always after login, I am forwarded to the profile page)
In order to reproduce please provide specific browsers , OS and ruby/rails version

**Comment by LucianU** [comment]
@ancazapuc9, nici eu nu pot reproduce cu setup-ul de Vagrant. Totuși problema apare în producție pe comunitate.code4.ro. Am testat cu Chrome 58 pe macOS Sierra 10.12.5. Poți să confirmi că-ți apare și ție?

În producție folosim același stack ca în setup-ul de Vagrant: Rails 5.0.0.1 și ruby 2.3.4p301.

**Comment by ancazapuc9** [comment]
After searching come up with following thread -> 
[Solution1 ](https://github.com/xargr/rails_deploy/issues/2 )
Similar with [Solution 2](https://gist.github.com/maxivak/a25957942b6c21a41acd)

stacktrace appears to be the same as the guy mentioned:
```
#<ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken>
/www/comunitate.staging.code4.ro/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/request_forgery_protection.rb:195:in `handle_unverified_request'
/www/comunitate.staging.code4.ro/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/request_forgery_protection.rb:223:in `handle_unverified_request'
/www/comunitate.staging.code4.ro/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/request_forgery_protection.rb:218:in `verify_authenticity_token'

```
Add his fix and Safari and Chrome work now.
@LucianU  please let me know on what other browsers should we test.

**Comment by LucianU** [comment]
Fixed in #106.
