### ISSUE TITLE
Adaugă posibilitatea de a da drept de admin din interfață

### ISSUE THREAD

**Issue by LucianU** [code4romania/volunt-app#7]
Vrem să putem da drept de fellow sau coordinator direct din interfață.
@shotgundebugging, știi dacă se poate face asta? Dacă nu există funcționalitatea, vrei să te ocupi tu?

**Comment by vitaliel** [comment]
Acum se poate seta doar la aplicant și voluntar.

**Comment by LucianU** [comment]
Implementat în #15.
