### ISSUE TITLE
Adaugă acorduri de bifat

### ISSUE THREAD

**Issue by LucianU** [code4romania/volunt-app#87]
Asta înseamnă că vrem ca utilizatorul să confirme că a citit codul de conduită și că nu e afiliat vreunui partid. Doar apoi se poate înscrie.

**Comment by vitaliel** [comment]
Pe care pagină trebuie să fie bifa? un mockup ar fi binevenit.

**Comment by LucianU** [comment]
În josul paginii, pe formularul pe care se înscrie utilizatorul după ce a introdus emailul. Ar trebui să fie obligatorii și să arate cam așa:

x Nu sunt asociat(ă) cu un partid politic
x Am citit [Codul de Conduită](http://code4.ro/codul-de-conduita/)
