### ISSUE TITLE
Adaugă un câmp de observații pe profilul utilizatorului

### ISSUE THREAD

**Issue by LucianU** [code4romania/volunt-app#9]
Câmpul va fi vizibil doar de fellows sau colaboratori. În el adminii vor pune feedback legat de interacțiunile cu userul respectiv.

**Comment by vitaliel** [comment]
@LucianU 

Poate e mai bine să adauge comentarii pentru profil?

Așa se va vedea interacțiunea în timp.

**Comment by LucianU** [comment]
@vitaliel, vrei să spui să avem mai multe comentarii pe un profil și nu doar un câmp? Adică, să existe un buton Adaugă comentariu pe care să-l vadă fellows și să poată adăuga comentarii multiple?

**Comment by vitaliel** [comment]
@LucianU da

**Comment by LucianU** [comment]
E mai simplu să rămână un câmp momentan, după cum a spus Maria.

**Comment by LucianU** [comment]
Implementat în #16.
